version: '3.8'
services:
  cms-frontend:
    build: .
    ports:
      - '80:80'
    container_name: cms-frontend
    restart: always
    environment:
      - VITE_API_BASE_URL=https://localhost:6001
