version: '3.4'

services:
  cmsdb:
    container_name: cmsdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    restart: always
    ports:
      - "1433:1433"
  # cms.api:
  #   depends_on:
  #     - cmsdb
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #     - ASPNETCORE_HTTPS_PORTS=8081
  #     - ASPNETCORE_Kestrel__Certificates__Default__Password=pass123
  #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
  #     - ConnectionStrings__Database=Data Source=cmsdb;Initial Catalog=CmsDb;User ID=sa;Password=${SA_PASSWORD};Encrypt=False;Trust Server Certificate=True
  #     - Domain__HttpHost=http://localhost:5001
  #     - Domain__HttpsHost=https://localhost:6001
  #     - StaticFiles__UploadedDirectory=UploadedFiles
  #   ports:
  #     - "5001:8080"
  #     - "6001:8081"
  #   volumes:
  #     - ./:/https:ro
